### ISSUE TITLE
Listing directories not working with FileZilla server

### ISSUE THREAD

**Issue by Xfel** [robtimus/ftp-fs#1]
When I try to list directory contents stored on a FileZilla server, I always get a `java.nio.file.NotDirectoryException`. This seems to come from the fact that FileZilla doesn't emit `.` when using the `LIST` command.

**Comment by robtimus** [comment]
That would break a few other methods as well, at least for empty folders. I think it's not limited to FileZilla though, but possibly all Windows FTP servers.

I will need to find other such cases, and see if I can solve these. Some would require finding the folder in the parent folder. That would be a performance hit though, especially for folders with many files and sub folders.

**Comment by robtimus** [comment]
I've just created a release that should fix this. I've made sure that both with and without `.` are automatically supported, with unit tests for both cases. There should be no need to do anything in using code.

Please note that not all attributes of the root folder (`/`) will be available, as the root folder cannot be returned as part of a `LIST` command. The only thing that will be available is its type (directory).
