### ISSUE TITLE
Server Reply: SSH-2.0-OpenSSH_7.4

### ISSUE THREAD

**Issue by kagami001** [robtimus/ftp-fs#15]
Thank you for sharing your work, it really helps me

I meet some problem when i try to connect my server by ftps, it returns:

> org.apache.commons.net.MalformedServerReplyException: Could not parse response code. Server Reply: SSH-2.0-OpenSSH_7.4

Here is my code:
```java
public void syncImages() throws URISyntaxException, IOException { 
        FTPSEnvironment env = new FTPSEnvironment()
                .withCredentials("root", "123456".toCharArray());
        FileSystem server = FileSystems.newFileSystem(URI.create("ftps://10.146.168.39"), env);
        Path path = server.getPath("/data/app/mobile-materials/public/img/");
        int a = 1;
    }
```

How can i solve this problem?

Thank you

**Comment by kagami001** [comment]
> I've checked Apache Commons NET to see where this exception is thrown. It's when an FTP server response does not start with an FTP status code. I think you're trying to use FTPS where you need to use SFTP. When I searched for this error, I found https://stackoverflow.com/a/20677498/1180351 which seems to indicate that.
> 
> Can you try using [sftp-fs](https://github.com/robtimus/sftp-fs/) instead? You'll need to make some changes:
> 
> * Use `SFTPEnvironment` instead of `FTPSEnvironment`
> * Use `withUsername`, `withPassword` and possibly `withHostKeyRepository` instead of `withCredentials`; see [providing credentials](https://github.com/robtimus/sftp-fs/#providing-credentials)
> * Use "sftp://" instead of "ftps://" in the

**Comment by kagami001** [comment]
Thank you for answering my question, and I have solved my problem. As you say, I should use sftp-fs instead.
I have met the exception which looks like `com.jcraft.jsch.JSchException: UnknownHostKey: `  when I work with the sftp-fs, and I write my solution below.

1. You need to get the public key file which usually called `known_hosts`. There are many ways to get it, one of them is as below. The file will generate in current directory.
```Java
JSch jsch=new JSch();
Session session=jsch.getSession(user, host, 22);
session.setPassword(password);
session.setConfig("StrictHostKeyChecking", "no");
session.connect();
```

2. The method `withHostKeyRepository` takes a `HostKeyRepository`, and you can get it by the method `get HostKeyRepository ` of a `JSch` instance. Pay attention that you are going to use the `known_hosts` file which is mentioned above while creating the JSch instance. Here is my code.
```Java
JSch jsch=new JSch();
jsch.setKnownHosts(known_hosts);
jsch.getHostKeyRepository();
```

**Comment by robtimus** [comment]
@kagami001 I was thinking that I should add something to make it easier. While I was investigating how to do that, I noticed I already added method `withKnownHosts(File)` to `SFTPEnvironment` in version 1.2. You may want to use that, it's a bit easier than creating a `JSch` instance yourself.

Also, the `StrictHostKeyChecking` can be set on `SFTPEnvironment` instances as well using one of the `withConfig` methods, if you'd prefer that.

**Comment by kagami001** [comment]
That’s awesome, I didn’t notice this usage. It makes my code cleaner. Thank you.

**Comment by robtimus** [comment]
You're welcome.
