### ISSUE TITLE
 Paths.getPath() not working

### ISSUE THREAD

**Issue by stefanofornari** [robtimus/ftp-fs#17]
Reporting here https://github.com/robtimus/sftp-fs/issues/14#issue-2000503081 as I am first dealing with ftp.

**Comment by stefanofornari** [comment]
See https://github.com/sshtools/vfs2nio for an approach to configuration/authentication you may consider

**Comment by robtimus** [comment]
I've just released version 3.2 which improves both `newFileSystem` and `getPath`.
