### ISSUE TITLE
unused FTPLogger class

### ISSUE THREAD

**Issue by sekaijin** [robtimus/ftp-fs#9]
Hello

I noticed that the FTPLogger class is never used.
the only reference is in FTPClientPool and this is just the call to createLogger that just encapsulates LoggerFactory.getLooger of SLf4J.
I do not understand the presence of this class.

A+JYT

**Comment by robtimus** [comment]
It was added for https://github.com/robtimus/ftp-fs/pull/8 to provide logging. It indeed encapsulates an SLF4J Logger, but it also provides i18n support without adding that burden to `FTPClientPool`. It also allows me to easily add more logging if necessary.
